//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FDiver.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_ACT_FIND                    100
#define IDR_OPT_FIND                    101
#define IDR_ACT_OPENFOLDER				102
#define IDR_ACT_FINDSTOP                103
#define IDR_ACT_TOPMOST                 104
#define IDR_ACT_CLEARSEL                105
#define IDR_ACT_DISPDOC                 107
#define IDR_ACT_DISPDOCEDIT             108
#define IDR_ACT_EDITER                  109
#define IDR_OPT_ICON                    110
#define IDR_ACT_CHGPATH                 111
#define IDR_ACT_SORTLST                 115
#define IDR_ACT_DISPDOC2                116
#define IDR_DSP_CLOSETODIR              117
#define IDR_DSP_CLOSETOFILE             118
#define IDR_DSP_SORTBYNAME              119
#define IDR_DSP_SORTBYEXP               120
#define IDR_DSP_SORTBYSIZE              121
#define IDR_DSP_SORTBYDATE              122
#define IDR_OPT_DISPTREE                123
#define IDR_OPT_DISPBYPATH              124
#define IDR_OPT_DISPLIST                125
#define IDR_OPT_DISPBYFILE              126
#define IDR_OPT_DRAG_SERVER             127
#define IDR_MAINFRAME                   128
#define IDR_FDIVERTYPE                  129
#define IDR_OPT_KEYENTRY                131
#define IDB_TREE                        131
#define IDR_CREJIT                      132
#define IDR_POPUP                       132
#define IDR_OPT_DSPFINDLOG              133
#define IDD_DIALOG1                     133
#define IDR_POPMENU_EDIT                133
#define IDR_OPT_DISPDOC                 135
#define IDR_OPT_DISPNUM_NO              136
#define IDR_OPT_DISPNUM_BYTES           137
#define IDD_SPLASH                      137
#define IDR_OPT_DISPNUM_LINES           138
#define IDB_BITMAP1                     138
#define IDR_DSP_DIR                     139
#define IDB_FDIVER_WELCOM               139
#define IDR_DSP_SHORT                   140
#define IDR_APP_EXIT                    155
#define IDD_COLORS                      171
#define IDD_CREJIT                      201
#define IDD_FIND                        202
#define IDD_OPTIONS                     203
#define IDD_FINDOPTION                  204
#define IDD_DSPOPTION                   205
#define IDD_EXTENSIONS                  206
#define IDD_META_CHARS                  207
#define IDD_FILETRANS                   208
#define IDD_INPUTSTRDLG_NEW             210
#define IDD_INPUTSTRDLG_CHG             211
#define IDD_ASSOOPTION                  212
#define IDD_FILESPEC                    213
#define IDD_STRSPEC                     214
#define IDD_STRSPEC_JPN                 215
#define IDD_STRSPEC_US                  216
#define IDD_EDSTRLST                    217
#define IDD_META_INPUT1                 218
#define IDD_META_INPUT2                 219
#define IDD_META_INPUT                  220
#define IDD_EDSTRLST2                   221
#define IDD_INPUTSTRDLG_CHG2            222
#define IDD_INPUTSTRDLG_NEW2            223
#define IDD_PATH                        224
#define IDD_FINDLOG                     225
#define IDB_LSTENT1                     260
#define IDB_FILE                        261
#define IDB_PATH                        262
#define IDB_LINE                        263
#define IDB_DOWN                        264
#define IDI_FINDING                     270
#define IDI_FINDING2                    271
#define ID_FINDITEMS                    280
#define ID_SEARCHFILES                  281
#define ID_FINDDOING                    282
#define ID_FINDFILES                    283
#define ID_FINDDIRS                     284
#define IDC_OF_POSITION                 301
#define IDC_F_PAST                      307
#define IDC_F_FILE_DROP                 308
#define IDC_OF_ASSO_OTHERS              317
#define IDC_OF_STRFILE                  318
#define IDC_OF_STRFILE_BTN              319
#define IDC_OF_DRAG_SERVER              321
#define IDC_OF_ASSO_EDITER              323
#define IDC_OF_ASSO_SANSYO              324
#define IDC_OF_ASSO_TXT                 325
#define IDC_F_SETSTRSPEC                351
#define IDC_F_SETMETHODSPEC             353
#define IDC_F_CMB_STRSPEC               356
#define IDC_FS_IGN_CASE                 359
#define IDC_FS_IGNO_BYTES               360
#define IDC_FS_IGNO_KATA                361
#define IDC_FS_NO_SPACE                 362
#define IDC_FS_NO_TAB                   363
#define IDC_FS_NO_LF                    364
#define IDC_FS_NO_OTHER_ED              366
#define IDC_FS_IGNO_UMURA               367
#define IDC_FS_NO_NOBRAK                368
#define IDC_ESL_NAME                    371
#define IDC_ESL_NEW                     372
#define IDC_ESL_CHG                     373
#define IDC_ESL_LIST                    374
#define IDC_ESL_UP                      376
#define IDC_ESL_DOWN                    377
#define IDC_F_SYSFILE                   378
#define IDC_F_HIDEFILE                  379
#define IDC_F_PRGFILE                   380
#define IDC_F_DOCFILE                   381
#define IDC_F_OTHERFILE                 382
#define IDC_ANCHOR3                     384
#define IDC_F_TITESEARCH                385
#define IDC_META_MATCHANY               387
#define IDC_META_MATCHSTR               388
#define IDC_META_AND                    389
#define IDC_META_OR                     390
#define IDC_META_XOR                    391
#define IDC_META_NOT                    392
#define IDC_META_BLOCK_L                393
#define IDC_META_BLOCK_R                394
#define IDC_META_PREFIX                 395
#define IDC_META_SBLOCK_L               396
#define IDC_META_SBLOCK_R               397
#define IDC_META_SOR                    398
#define IDC_META_SXOR                   399
#define IDC_META_STNDARD                400
#define IDC_META_BASIC                  401
#define IDC_META_INFO                   402
#define IDC_F_META_INPUT                403
#define IDC_META_INPUT                  404
#define IDC_KICK_APP_START              405
#define IDC_KICK_APP_END                419
#define IDC_KICK_APP_OTHER              420
#define IDC_OF_STRFILE2                 421
#define IDC_OF_MAXLINES                 422
#define IDC_DEFTAG_AUTO                 425
#define IDC_OF_METAHELP                 426
#define IDC_MITOROKU                    428
#define IDC_OF_NOERRDSP                 429
#define IDC_FINDLOG_EDIT                431
#define IDC_FT_LHA                      432
#define IDC_FT_ZIP                      433
#define IDC_FT_WORKPATH                 434
#define IDC_FT_NOREMAIN                 435
#define IDC_FT_HITREMAIN                436
#define IDC_FT_ARJ                      437
#define IDC_FT_TAR                      438
#define IDC_FT_CAB                      439
#define IDC_FT_RAR                      440
#define IDC_FT_KFT                      441
#define IDC_FT_XDOC                     442
#define IDC_F_OK                        445
#define IDC_DRP_NG                      446
#define IDC_F_STRING                    447
#define IDC_DRP_SINGLE                  448
#define IDC_F_FILE                      449
#define IDC_F_PATH                      450
#define IDC_F_SUBDIR                    451
#define IDC_F_SETPATH                   452
#define IDC_F_SETPATH_FOLDER            453
#define IDC_OF_DISPDOC                  454
#define IDC_OF_READSIZE                 455
#define IDC_OF_SOUND                    456
#define IDC_OF_TOPWIN                   457
#define IDC_OF_GYOUNUM                  458
#define IDC_OF_BYTENUM                  460
#define IDC_OF_ICON                     464
#define IDC_TIMER_USERID                466
#define IDC_TIMER_TIME                  468
#define IDC_CRJTMPID                    469
#define IDC_F_NOTIME                    473
#define IDC_F_TODAY                     474
#define IDC_F_YESTERDAY                 475
#define IDC_F_THISWEEK                  476
#define IDC_F_SETDAY                    477
#define IDC_F_FROMDAY                   478
#define IDC_F_FROMHOUR                  480
#define IDC_F_GODAY                     481
#define IDC_F_GOHOUR                    482
#define IDC_ANCHOR                      483
#define IDC_ANCHOR2                     484
#define IDC_F_SETFILESPEC               485
#define IDC_OF_DIR                      498
#define IDC_OF_ATTR                     499
#define IDS_META_MATCHANY               600
#define IDS_META_MATCHSTR               601
#define IDS_META_AND                    602
#define IDS_META_OR                     603
#define IDS_META_XOR                    604
#define IDS_META_NOT                    605
#define IDS_META_BLOCKL                 606
#define IDS_META_BLOCKR                 607
#define IDS_META_PREFIX                 608
#define IDS_META_SBLOCK_L               609
#define IDS_META_SBLOCK_R               610
#define IDS_META_SOR                    611
#define IDS_META_SXOR                   612
#define IDS_META_RLERR                  613
#define IDS_META_RLFALSE                614
#define IDS_META_RLTRUE                 615
#define IDS_META_TAB1                   616
#define IDS_META_TAB2                   617
#define IDS_STRSPEC_ENT1                618
#define IDS_OPT_FILE_ENTRY              619
#define IDS_STRSPEC_ENT2                620
#define IDS_CRJ_OK                      621
#define IDS_CRJ_NG                      622
#define IDS_CRJ_OVER                    623
#define IDS_CRJ_TIMERERR                624
#define IDS_ACTEDITER_ERR               625
#define IDS_WRITEOPT_DISKERR            626
#define IDS_TIMELAGEERR                 627
#define IDS_TIMESETERR                  628
#define IDS_OVERMEM_FORLST              629
#define IDS_ASSO_ERR                    630
#define IDS_OPENDOC_ERR                 631
#define IDS_OPT_FILETYPE                632
#define IDS_XDOC_TRANS                  633
#define IDS_NOMEM_READBUFF              634
#define IDS_NOSYSMEM                    635
#define IDS_PATHDLG_TITLE               636
#define IDS_TITESEARCH                  637
#define IDS_STBAR_STOP                  638
#define IDS_DIBING                      639
#define IDS_DISPLIST                    640
#define IDS_EXTENSIONS                  641
#define IDS_METACHARS                   642
#define IDS_FILETRANS                   643
#define IDS_CANNOTOPEN                  644
#define IDS_STRMODE_JPN                 645
#define IDS_STRMODE_US                  646
#define IDS_STBAR_ENDSCAN               647
#define IDS_SAMENAME_ERR                648
#define IDS_PLEASE_KEYWORD              649
#define IDS_PLEASE_INPUTCHAR            650
#define IDS_TOLARGETIME_ERR             651
#define IDS_PLEASE_INPUTTIME            652
#define IDS_ENTRYNAME                   653
#define IDS_OVERENTRY_FORLST            654
#define IDS_ERR_METASTRENTRY_LOOP       656
#define IDS_TAG_OPEN                    657
#define IDS_TAG_SAVE_AS                 658
#define IDS_VERDOC_ERR                  660
#define IDS_ERR_FILEOPEN                661
#define IDS_STBAR_NOTFOUND              662
#define IDS_INVAL_PATH                  663
#define IDS_ARC_EXTRACT                 664
#define IDS_KFT_TRANS                   665
#define IDS_EXECUTE                     666
#define IDS_KICK_APPS                   667
#define IDS_ERR_NOREAY_NET_DRV          668
#define IDD_DEL_PRONPT                  800
#define IDC_DEL_ALL                     820
#define IDC_DEL_FILENAME                821
#define IDC_EDITER                      822
#define IDC_REF_BTN                     823
#define IDC_F_ARC                       824
#define IDS_MSG_TAGTEXT_ERR_CREATE      825
#define IDS_MSG_TAGTEXT_ERR_WRITE       826
#define IDS_MSG_TAGTEXT_HOWTOUSE        827
#define IDS_MSG_SHOW_MAN                828
#define IDS_KICK_APP_OTHER              829
#define IDS_ACTCLONE_ERR                830
#define ID_CHANGE_COLOR                 1001
#define IDC_CHKCR_EDITER                1002
#define IDC_OF_EXTRA_FILESPEC           1003
#define IDC_BTN_BROWSE                  1004
#define IDC_F_SXW                       1005
#define IDC_F_SXC                       1006
#define IDC_BMP_SPLASH                  1006
#define IDC_F_SXI                       1007
#define IDC_F_SXD                       1008
#define IDC_F_DOCX                      1009
#define IDC_EDT_RATIO_BETWEEN_LINE      1009
#define IDC_F_XLSX                      1010
#define IDC_SPIN1                       1010
#define IDC_SPN_RATIO_BETWEEN_LINE      1010
#define IDC_F_PPTX                      1011
#define IDC_F_DOC                       1013
#define IDC_F_XLS                       1014
#define IDC_F_PPT                       1015
#define IDC_F_WRI                       1016
#define IDC_F_JAW                       1017
#define IDC_F_JBW                       1018
#define IDC_F_JFW                       1019
#define IDC_F_JTD                       1020
#define IDC_F_ODT                       1021
#define IDC_F_ODS                       1022
#define IDC_F_ODP                       1023
#define IDC_F_ODG                       1024
#define IDC_F_PDF                       1025
#define IDC_F_HTML                      1026
#define IDC_F_EML                       1027
#define IDC_F_OAS                       1028
#define IDC_F_BUN                       1029
#define IDC_F_123                       1030
#define IDC_F_PDF2                      1031
#define IDC_F_RTF                       1031
#define stc1                            0x0440
#define lst1                            0x0460
#define lst2                            0x0461
#define IDC_LST_COLOR                   1121
#define cmb1                            0x0470
#define cmb2                            0x0471
#define edt1                            0x0480
#define IDR_DSP_LISTFONT                32783
#define ID_VIEW_HEADERBAR               32791
#define IDR_ACT_TAGTEXT                 32792
#define IDR_DSP_COLORS                  32793
#define IDR_DSP_OPENLIST                32794
#define IDR_ACT_KFT_TRANS_VIEW          32795
#define IDR_EDIT_COPY_3                 32796
#define IDR_EDIT_COPY_1                 32797
#define IDR_EDIT_COPY_10                32798
#define IDR_EDIT_COPY_ALL               32799
#define IDR_EDIT_DELL_FILE              32800
#define IDR_EDIT_DELL_ITEM              32801
#define IDR_EDIT_REF_FILE               32802
#define IDR_EDIT_ASC_FOLDER             32803
#define ID_MYHELP_INDEX                 32804
#define IDR_ZOOM_OUT                    32805
#define IDR_ZOOM_IN                     32806
#define ID_32807                        32807
#define ID_32808                        32808
#define IDR_ACT_CLONE                   32812
#define ID_FILE_MRU_FILE17              57638

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
